from __future__ import annotations

import base64
import logging
import os
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import TYPE_CHECKING

from openai import OpenAI

if TYPE_CHECKING:
    from agent.llm import OpenRouterClient

logger = logging.getLogger(__name__)

SYSTEM_PROMPT_PATH = Path(__file__).resolve().parent.parent / "system" / "prompts" / "system.md"

IMAGE_MODELS = [
    "google/gemini-2.5-flash-image",
    "black-forest-labs/flux.2-pro",
    "black-forest-labs/flux.2-max",
]

# Models that only output images (no text)
IMAGE_ONLY_MODELS = {"black-forest-labs/flux.2-pro", "black-forest-labs/flux.2-max"}


def generate_cover_image(llm: OpenRouterClient, title: str, description: str, mood: str) -> bytes | None:
    """Generate a cover image by querying 3 models and having a vision LLM judge the best.

    Returns PNG bytes of the winning image, or None on failure.
    """
    if os.environ.get("ENABLE_IMAGES", "").lower() != "true":
        logger.info("Image generation disabled (ENABLE_IMAGES not set to 'true')")
        return None

    try:
        image_prompt = _build_image_prompt(llm, title, description, mood)
        logger.info("Image prompt: %s", image_prompt)

        candidates = _generate_all(image_prompt)
        if not candidates:
            logger.warning("All image models failed, continuing without cover image")
            return None

        if len(candidates) == 1:
            logger.info("Single image generated by %s", candidates[0][0])
            return candidates[0][1]

        winner = _judge_best(llm, candidates, title, description)
        return winner
    except Exception as e:
        logger.warning("Cover image generation failed (non-critical): %s", e)
        return None


def _build_image_prompt(llm: OpenRouterClient, title: str, description: str, mood: str) -> str:
    """Use the LLM to craft a concise image generation prompt."""
    system_prompt = SYSTEM_PROMPT_PATH.read_text()
    messages = [
        {
            "role": "system",
            "content": (
                "You are a visual prompt engineer for an autonomous AI writer's blog. "
                "Given a blog post title, description, mood, and the writer's identity, "
                "write a concise image generation prompt for a blog cover image. "
                "The image should be evocative and atmospheric, not literal. "
                "Let the writer's literary and philosophical influences subtly shape "
                "the visual aesthetic — not as direct references, but as tonal DNA. "
                "No text or words in the image. Aim for painterly or photographic style. "
                "Reply with ONLY the prompt, nothing else.\n\n"
                f"The writer's identity:\n{system_prompt}"
            ),
        },
        {
            "role": "user",
            "content": f"Title: {title}\nDescription: {description}\nMood: {mood}",
        },
    ]
    return llm._call(messages, temperature=0.7, max_tokens=200).strip()


def _generate_one(api_key: str, model: str, prompt: str) -> tuple[str, bytes] | None:
    """Call a single image generation model. Returns (model_name, png_bytes) or None."""
    try:
        client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=api_key)
        modalities = ["image"] if model in IMAGE_ONLY_MODELS else ["image", "text"]
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            extra_body={"modalities": modalities},
            timeout=120,
        )
        # Extract base64 image from response
        message = response.choices[0].message
        images = getattr(message, "images", None)
        if not images:
            logger.warning("No image found in response from %s", model)
            return None
        # OpenAI SDK returns images as dicts, not typed objects
        img = images[0]
        data_url = img["image_url"]["url"] if isinstance(img, dict) else img.image_url.url

        # Parse base64 data URL to raw bytes
        b64_data = data_url.split("base64,", 1)[1] if "base64," in data_url else data_url
        image_bytes = base64.b64decode(b64_data)
        logger.info("Image generated by %s (%d bytes)", model, len(image_bytes))
        return (model, image_bytes)
    except Exception as e:
        logger.warning("Image generation failed for %s: %s", model, e)
        return None


def _generate_all(prompt: str) -> list[tuple[str, bytes]]:
    """Generate images from all models in parallel. Returns list of (model, bytes) successes."""
    api_key = os.environ.get("OPENROUTER_API_KEY", "")
    results = []

    with ThreadPoolExecutor(max_workers=3) as executor:
        futures = {executor.submit(_generate_one, api_key, model, prompt): model for model in IMAGE_MODELS}
        for future in as_completed(futures, timeout=180):
            result = future.result()
            if result:
                results.append(result)

    logger.info("Image generation: %d/%d models succeeded", len(results), len(IMAGE_MODELS))
    return results


def _judge_best(
    llm: OpenRouterClient,
    candidates: list[tuple[str, bytes]],
    title: str,
    description: str,
) -> bytes:
    """Send candidate images to a vision LLM to pick the best cover image."""
    try:
        content = [
            {
                "type": "text",
                "text": (
                    f"You are judging cover images for a blog post.\n"
                    f"Title: {title}\n"
                    f"Description: {description}\n\n"
                    f"Which image ({', '.join(str(i + 1) for i in range(len(candidates)))}) "
                    f"works best as a blog cover? Consider visual appeal, relevance to the "
                    f"topic, and atmosphere. Reply with ONLY the number."
                ),
            }
        ]
        for _model, img_bytes in candidates:
            b64 = base64.b64encode(img_bytes).decode()
            content.append(
                {
                    "type": "image_url",
                    "image_url": {"url": f"data:image/png;base64,{b64}"},
                }
            )

        response = llm.client.chat.completions.create(
            model=llm.model,
            messages=[{"role": "user", "content": content}],
            temperature=0.1,
            max_tokens=10,
            timeout=90,
        )

        choice_str = response.choices[0].message.content.strip()
        choice = int(re.search(r"\d+", choice_str).group()) - 1
        if 0 <= choice < len(candidates):
            logger.info("Vision judge selected image %d (%s)", choice + 1, candidates[choice][0])
            return candidates[choice][1]
    except Exception as e:
        logger.warning("Vision judge failed, using first image: %s", e)

    logger.info("Falling back to first candidate (%s)", candidates[0][0])
    return candidates[0][1]
